### ISSUE TITLE
Mavericks Sandbox 

### ISSUE THREAD

**Issue by davidwuest** [pklaus/mac_click2dial_sipgate#5]
The problem with Mavericks is that the Sandbox is blocking write access because of calling to an external URL.

Contacts(35345) deny file-write-create /Users/davidwuest/Library/Address Book Plug-Ins/SipgateClickToDial.bundle/Contents/Resources/sipgate.pyc

Can anyone help to fix this?

**Comment by mohataj** [comment]
It currently crashes with a codesigning error

13.05.14 00:25:55,000 kernel[0]: CODE SIGNING: process 79021[Contacts]: rejecting invalid page at address 0x10cae5000 from offset 0x1000 in file "/Users/mo/Library/Address Book Plug-Ins/SipgateClickTodial.bundle/Contents/Frameworks/Python.framework/Versions/2.6/Python" (cs_mtime:1399933187.0 == mtime:1399933187.0) (signed:1 validated:1 tainted:1 wpmapped:0 slid:0)
